### ISSUE TITLE
invalid release.json files

### ISSUE THREAD

**Issue by torkus** [NinerBull/tRP3_RPNameInQuests#1]
hi @NinerBull , 

I compile [a catalogue of WoW addons hosted on Github](https://github.com/ogri-la/github-wow-addon-catalogue-go) once a week and noticed some of your addons went missing today: 

* NinerBull/AccWideUILayoutSelection
* NinerBull/NPCRPGossip
* NinerBull/tRP3_RDotIO
* NinerBull/tRP3_RPNameInQuests

Upon inspection it looks like the `release.json` files are invalid, missing the `nolib` field. The previous releases look fine.

Frustrated at the lack of a specification myself I created one here:
https://github.com/ogri-la/release.json-specification

As well as a validator if you're interested (feedback welcome):
https://github.com/ogri-la/release.json-validator

I was able to validate ~1.7k `release.json` files and was surprised at how uniformly valid they all were, probably because they were all generated by the same program. May I ask what you used to create those `release.json` files?

**Comment by NinerBull** [comment]
Hey there!

Thanks for the message and links. I've been doing them by hand, wasn't sure what the nolib field was for, but now I do!

I've added it back into the release.json for all 4 repos, can you check and see if they look ok?

Thanks,
//Conine

**Comment by torkus** [comment]
Just checked them and they all looked valid:

* tRP3_RPNameInQuests
* NinerBull/tRP3_RDotIO
* NinerBull/NPCRPGossip
* NinerBull/AccWideUILayoutSelection

Thanks for touching them up.

Best.

**Comment by torkus** [comment]
> ..., wasn't sure what the nolib field was for, but now I do!

A drawback of JSON/JSONSchema is that it can't be annotated with comments.

`nolib` addons are a release of an addon without the libraries it ordinarily depends on. They're usually smaller and used for bundling within other addons or for those interested in very carefully controlling addon dependencies.
